field: e3ff44b3-f83b-4c78-8582-dca947852212 # Faq
fieldLayouts:
  39576acc-ee05-42cd-8987-b62d29e4c519:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d96a1f0a-183e-4b79-b347-4ff9c88d1578 # Question
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ca07e87a-fbd2-4e5d-88ac-451bcd5fbf6f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4fffb709-b4db-4f93-8f04-8a44ac4f9dd1 # Answer
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a87408c0-83f9-4ac5-9150-b2b99222426e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5a5025de-6808-49cc-9775-d25b3fae6e60
        userCondition: null
fields:
  4fffb709-b4db-4f93-8f04-8a44ac4f9dd1: # Answer
    columnSuffix: pbgbmrkv
    contentColumnType: text
    fieldGroup: null
    handle: answer
    instructions: null
    name: Answer
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  d96a1f0a-183e-4b79-b347-4ff9c88d1578: # Question
    columnSuffix: kqkvazlg
    contentColumnType: text
    fieldGroup: null
    handle: question
    instructions: null
    name: Question
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: faqblock
name: 'Faq Block'
sortOrder: 1
