field: 51c9e0c1-aa98-45b5-8275-0e325f868e1b # Press Content
fieldLayouts:
  0e782016-fc99-4833-aa14-5385cd38eabc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 5f20b2d7-2cff-4088-8b97-6e8976ae0f25 # Press Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 016319c2-c669-4c1a-9ac2-951a23d718b1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fc76696d-3b3f-4e74-827f-f6b10458960c # Press Url
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 20c7e325-50f7-4e0f-9b07-96391926e638
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 18471c2e-e18a-4434-a562-4539acd570d6
        userCondition: null
fields:
  5f20b2d7-2cff-4088-8b97-6e8976ae0f25: # Press Name
    columnSuffix: rqssqdbp
    contentColumnType: text
    fieldGroup: null
    handle: pressName
    instructions: null
    name: 'Press Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  fc76696d-3b3f-4e74-827f-f6b10458960c: # Press Url
    columnSuffix: tesejtjw
    contentColumnType: string(255)
    fieldGroup: null
    handle: pressUrl
    instructions: null
    name: 'Press Url'
    searchable: false
    settings:
      maxLength: 255
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
handle: pressblock
name: PressBlock
sortOrder: 1
