field: 3248c17c-cc92-47f8-826f-90c8c4813952 # Top Podcast Content
fieldLayouts:
  7f41fe10-08f6-4458-8231-e9b3dbbb31d5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 41fe3bdd-3f5c-4af3-962a-eedc09c933bd # Top Podcast Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 22f767d4-8796-4fb5-8ca1-0a943b2a9363
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cd57f38c-008a-40e6-bf57-579eaa50b868 # Top Podcast Url
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ade3c003-d382-4aa9-bae9-3c351f481edc
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0e764ddc-b6c1-4848-9d05-8447087ac01f
        userCondition: null
fields:
  41fe3bdd-3f5c-4af3-962a-eedc09c933bd: # Top Podcast Name
    columnSuffix: ljopmztg
    contentColumnType: text
    fieldGroup: null
    handle: topPodcastName
    instructions: null
    name: 'Top Podcast Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  cd57f38c-008a-40e6-bf57-579eaa50b868: # Top Podcast Url
    columnSuffix: wofychip
    contentColumnType: string(255)
    fieldGroup: null
    handle: topPodcastUrl
    instructions: null
    name: 'Top Podcast Url'
    searchable: false
    settings:
      maxLength: 255
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
handle: topPodcastBlock
name: 'Top Podcast Block'
sortOrder: 1
