fieldLayouts:
  c51efe31-3d04-47e9-986d-56ff88cc5ad4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 18d81268-0899-439c-823d-8421af5b0baa
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2448128b-6797-437f-aa93-a9f9c621eaef # Section Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a814fc86-7b78-42d3-9e2a-e6b3e0252152
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 98929c89-6516-4fc1-91bf-e9532d3a580c
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0736e646-b125-4b28-b91f-685300e33cce # Seo Fields
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d2fa1d9b-7476-4bdd-8fca-88eaf37831dc
            userCondition: null
            warning: null
            width: 100
        name: Seo
        uid: 7d53b7fc-301b-4915-a398-0540c7804512
        userCondition: null
handle: cookiePolicy
hasTitleField: false
name: 'Cookie Policy'
section: 01239f8a-12e9-4e25-be2e-a7bb2dfba484 # Cookie Policy
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
