fieldLayouts:
  f5949aab-39bc-4663-a94a-a61191c5c62b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 74114179-8b7e-4411-b212-cc7063bbcdb0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c3618ed8-17a8-4305-acff-a607897dc961
        userCondition: null
fs: seoImage
handle: seoImages
name: 'Seo Images'
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
