columnSuffix: null
contentColumnType: string
fieldGroup: 1bd6fa17-75b5-4faf-8078-4448965ac607 # Help Center
handle: faq
instructions: null
name: Faq
searchable: false
settings:
  contentTable: '{{%matrixcontent_faq}}'
  maxBlocks: null
  minBlocks: 1
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
