columnSuffix: null
contentColumnType: string
fieldGroup: 390cb4bc-fa07-4c31-a62e-4c1d0c6f2f44 # Header/Footer
handle: footerSideMenu
instructions: null
name: 'Footer Side Menu'
searchable: false
settings:
  contentTable: '{{%matrixcontent_footersidemenu}}'
  maxBlocks: null
  minBlocks: 1
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
