columnSuffix: oiecaexi
contentColumnType: string(255)
fieldGroup: 390cb4bc-fa07-4c31-a62e-4c1d0c6f2f44 # Header/Footer
handle: twitterUrl
instructions: null
name: 'Twitter Url'
searchable: false
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
