fieldLayouts:
  c8b2dfb1-8d81-4abd-9457-a616008fad10:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 264cda15-2932-4a8f-b484-2a80266750c2 # Footer Side Menu
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 863a6a1a-7f57-48ee-b52b-01d708833432
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: aaf86587-397a-4a6d-9b1d-b1316b836b49 # Logo Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7a4538c8-7829-4233-9f2d-b00cf30f1f00
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d46891d5-fe69-48ab-a028-ca1b8a9e4ed8 # Contact Email
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 245ce657-43b5-44ca-8f7e-87c365fb14f7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 26dc3c4a-3cad-43f7-895d-1fbda1e955e0 # Instagram Url
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9603ebd5-5820-49f7-bffa-c064dae84b05
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4bf4266f-b357-46cc-b49b-c34b3d7e5e7a # Twitter Url
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 64cdcee9-1f91-4d9c-a92b-74f353b4375f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 81b639db-0c4b-411a-90b9-c130764f196f # Copyright Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ca9c5436-d71a-4775-80d4-529d28f99036
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 60d0c738-d232-40ac-bb65-97181bf97557 # Footer Bottom Menu
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aa91633a-5bca-46a2-a0b1-4cfbf5c27fa6
            userCondition: null
            warning: null
            width: 100
        name: content
        uid: cda2e796-340a-456e-94c4-d5ace8ddd318
        userCondition: null
handle: siteFooter
name: 'Site Footer'
sortOrder: 2
