defaultPlacement: end
enableVersioning: true
handle: getStarted
name: 'Get Started'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  9f2120d1-04ae-459a-a917-c39f4bbfe29f: # Podspun
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: single
